### ISSUE TITLE
Enable pg_dump for this deployment

### ISSUE THREAD

**Issue by yogeshsajanikar** [cloudfoundry-community/phppgadmin-cf#3]
How can I enable pg_dump/pg_dumpall for cloud foundry deployment?

**Comment by ArthurHlt** [comment]
It actually save file in temp inside the containet (see: https://github.com/cloudfoundry-community/phppgadmin-cf/blob/cf-ready/conf/config.inc.php#L26-L27), you could alternatively use https://github.com/orange-cloudfoundry/db-dumper-service for this usecase

**Comment by yogeshsajanikar** [comment]
Actually, I did this by uploading pg_dump alongwith. It enabled me dumping database.
