### ISSUE TITLE
[question] installation to folder

### ISSUE THREAD

**Issue by dnsBlah** [cloudfoundry-community/phppgadmin-cf#4]
Is it possible to CF install this in a folder ?
So I got my project, and then folder phppgadmin to access the phppgadmin ?

**Comment by ArthurHlt** [comment]
Do you mean have phppgadmin right inside the main project folder ?
If yes, it must be possible if your app is in in php. But this is not recommended, it's better to use a dedicated app on Cloud Foundry.

**Comment by dnsBlah** [comment]
Hi Arthur,
thanks for your reply.
I do understand that also for security, it's wise to put it as a seperate app.
But for testing purposes I was more looking for a sollution like:
my CF app / phppgadmin

When I put this project in a folder within my app and push it, I get a message:
"This PHP installation was compiled without support for this type of database."

**Comment by ArthurHlt** [comment]
You have to add php extension on your app.
You can use an existing composer.json and add these dependencies:
```
    "ext-pgsql": "*",
    "ext-pdo_pgsql": "*",
```

Or add a folder called `.bp-config` with an `options.json` and put this: 
```json
{
"PHP_EXTENSIONS": ["bz2", "zlib", "curl", "mcrypt", "pgsql", "pdo_pgsql"],
}
```

see the doc from buildpack: http://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#php-extensions

**Comment by dnsBlah** [comment]
It's set, but when I'm running it from a 'subfolder' it's not working..
Will just put it on a seperate app.
Thanks for your help anyway

**Comment by ArthurHlt** [comment]
Could be interesting to try to investigate further. 
Can I see your config (project would be better) ? 
Is it the buildpack which give you this error ? 

I can't found this error on phppgadmin, and it's seems more to be a configuration error.

**Comment by dnsBlah** [comment]
I'm using SAP Hana Cloud Foundry from Yaas.io
Creating a project with the php buildpack, gives no problem at all.

When I extract the files to a folder within my local project.
(even if it's a index.php containing:
[code]
<?php
for($a=1;$a<5;$a++)
    echo '<h' . $a . '>Heading</h' . $a . '>';
[/code], or anything else)
The 'main folder' works as expected, but when calling the subfolder where I put phppgadmin in I get that message.
Using all same settings, but then just keep the phppgadmin files in the 'main' folder, no problems.
